### ISSUE TITLE
Drop support for older versions of Python?

### ISSUE THREAD

**Issue by movermeyer** [mc706/changelog-cli#18]
Given that this is a command line tool and not a library, perhaps we can keep pace with the [currently supported versions of Python](https://en.wikipedia.org/wiki/History_of_Python#Support) instead of all the versions?

Not only would we be able to make use of more modern syntax and features of the language, but we wouldn't have failures like our [recent failures in TravisCI](https://travis-ci.org/github/mc706/changelog-cli/jobs/753749230) where a development dependency has dropped support for those versions.

cc @mc706

**Comment by mc706** [comment]
Im certainly of two minds on the topic. All other things being equal, I do like help push the community forward for more periodic developments and language improvements, however I also know the pain of being in an environment where we were unable to upgrade for business reasons.

I would be in favor of dropping support of python 3 behind 3.6. Since OSX still ships with python2.7 as the default shell python, I would be hesitant to drop support for 2.7 as it is a barrier to entry for using the tool. Also any companies who havent upgraded would be 2.7.

That being said, if it is easier for dependency reasons to drop 2.7 and stay on 3.6+, I would also be happy with adding type hints everywhere and bringing the library up to date with latest python. Just a little bit concerned about adding arbitrary barriers to entry to use.

**Comment by movermeyer** [comment]
> That being said, if it is easier for dependency reasons to drop 2.7 and stay on 3.6+, I would also be happy with adding type hints everywhere and bringing the library up to date with latest python. Just a little bit concerned about adding arbitrary barriers to entry to use.

I agree on both points.

> still being the default python for a lot of unix systems https://github.com/mc706/changelog-cli/pull/19#issuecomment-761850240

* Ubuntu 20.01 changed the default to Python 3
* RHEL 8 changed the default to Python 3
* Arch's `python` package is Python 3
* Gentoo has Python 3 as the default
* [Fedora](https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3) has both installed by default
* openSUSE has both installed by default
* [Debian Bullseye](https://wiki.debian.org/DebianBullseye) (11) will change the default to Python 3. It's expected to be released later this year (~2021-07?). However, Debian already has `python3` also installed by default.

* MacOS ships with Python 2.7 as the default, but Homebrew has changed the `python` package to point to Python 3

* CentOS 8 still uses Python 2 by default
    * AlmaLinux is taking over? Future of CentOS is unclear.

I'm not sure the default matters anymore. Most of the market either has Python 3 installed by default, has it already installed as a dependency of any number of other things. Even in the rare case where it isn't already installed, it is really simple to install it alongside Python 2 (using [`pyenv`](https://github.com/pyenv/pyenv)).

**Comment by mc706** [comment]
Yeah i get where most of my developer pain has been in OSX development environments and onboarding new employees and telling a junior or mid level dev who hasnt done much proper engineering in python how to get setup. I guess at the point where you have a mature enough development environment, handling versions of python should be handled. 

In which case, ill approve the PR for dropping the older python versions from the pypi metadata and we should probably create some tasks for modernizing the codebase.

**Comment by mc706** [comment]
We should probably also remove the older versions from `README.md`

**Comment by movermeyer** [comment]
Unless I'm missing it somehow, the only mention of version numbers in the README is in the shields.io `pyversions` badge that will get updated when the next version is released.

**Comment by mc706** [comment]
Good catch, brain fart on my part. We can close this
